import React, { useCallback } from "react";import dayjs from "dayjs";import { useDashboard } from "../../services/dashboard/hooks";import { Loading, MonthPicker } from "@/components/ui";import { ShoppingBag, Store, Wallet } from "lucide-react";import { Page } from "@/components/app/layout";import { formatCurrency } from "@/utils";import { SummaryCard } from "@/components/app";import { SalesChart } from "@/components/dashboard";const CARD_THEMES = {
  green: { text: "text-green-500", iconBg: "#dcfce7", wave: "#22c55e" },
  blue: { text: "text-blue-500", iconBg: "#dbeafe", wave: "#3b82f6" },
  orange: { text: "text-orange-500", iconBg: "#ffedd5", wave: "#f97316" },};const DashboardPage: React.FC = () => {  const [periode, setPeriode] = React.useState(dayjs().format("YYYY-MM"));
  const {    getCommission,    getSales,    getItem,    getGraph,    sales,    isLoadingSales,    graph,    isLoadingGraph,  } = useDashboard();
  const fetchData = useCallback(() => {    const params = { periode };    getSales(params);    getItem(params);    getGraph(params);    getCommission(params);  }, [periode]);
  React.useEffect(() => {    fetchData();  }, [fetchData]);  const isLoading = isLoadingSales && !sales;
  return (    <Page className="h-full flex flex-col min-h-0 bg-slate-50">      <Page.Header        category="dashboard"        title="Dashboard"        subtitle="Ringkasan performa bisnis Anda hari ini."        action={
          <MonthPicker            value={periode}            onChange={setPeriode}          />        }
      />      <Page.Body className="flex flex-col gap-6">
        <SalesChart          data={graph?.data}          isLoading={isLoadingGraph}          selectedYear={parseInt(periode.split("-")[0])}          selectedMonth={periode.split("-")[1]}          onYearChange={(year) => setPeriode(`${year}-${periode.split("-")[1]}`)}          onMonthChange={(month) => setPeriode(`${periode.split("-")[0]}-${month}`)}        />        {isLoading ? (          <div className="flex items-center justify-center h-40">            <Loading size="lg" variant="spinner" />          </div>        ) : (          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">            <SummaryCard              label="Total Penjualan"              value={formatCurrency(sales?.total_sales || 0)}              icon={Wallet}              theme={CARD_THEMES.green}              variant="primary"            />            <SummaryCard              label="Total Transaksi"              value={sales?.total_orders || 0}              icon={ShoppingBag}              theme={CARD_THEMES.blue}              variant="primary"            />            <SummaryCard              label="Outlet Aktif"              value={sales?.total_outlets || 0}              icon={Store}              theme={CARD_THEMES.orange}              variant="primary"            />          </div>        )}      </Page.Body>    </Page>  );};
export default DashboardPage;
